# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('no', models.IntegerField()),
                ('userType', models.BooleanField()),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('bgType', models.CharField(max_length=2)),
                ('rhValue', models.BooleanField()),
            ],
        ),
    ]
